image: barichello/godot-ci:3.2.2


stages:
  - export
  - deploy

variables:
  EXPORT_NAME: godot

linux:
  stage: export
  only:
    - master
  script:
    - mkdir -v -p build/linux
    - cd $EXPORT_NAME
    - godot -v --export "Linux/X11" ../build/linux/$ITCHIO_GAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  only:
    - master
  script:
    - mkdir -v -p build/windows
    - cd $EXPORT_NAME
    - godot -v --export "Windows Desktop" ../build/windows/$ITCHIO_GAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

mac:
  stage: export
  only:
    - master
  script:
    - mkdir -v -p build/mac
    - cd $EXPORT_NAME
    - godot -v --export "Mac OSX" ../build/mac/$ITCHIO_GAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac

# Itch.io Deploy
itchio:linux:
  stage: deploy
  only:
    - master
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux --userversion-file version.txt
  dependencies:
    - linux

itchio:windows:
  stage: deploy
  only:
    - master
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows --userversion-file version.txt
  dependencies:
    - windows

itchio:macosx:
  stage: deploy
  only:
    - master
  script:
    - butler push ./build/mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac --userversion-file version.txt
  dependencies:
    - mac
